# Generated by Django 5.0.1 on 2026-01-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sfs_customers', '0001_initial'),
        ('sfs_inventory', '0001_initial'),
        ('sfs_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_validated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfs_inventory.stocklocation')),
            ],
            options={
                'db_table': 'daily_reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('channel', models.CharField(choices=[('KIOSK', 'Kiosque'), ('MARKET', 'Marché'), ('WEB', 'Web'), ('SUBSCRIPTION', 'Abonnement')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loyalty_points_used', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte'), ('CHECK', 'Chèque'), ('ONLINE', 'En ligne')], max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('COMPLETED', 'Complétée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('customer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=True)),
                ('offline_created_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sfs_customers.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfs_inventory.stocklocation')),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfs_products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sfs_sales.sale')),
            ],
            options={
                'db_table': 'sale_lines',
            },
        ),
    ]
