# Generated by Django 5.0.1 on 2026-01-27 16:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('KG', 'Kg'), ('UNIT', 'Unité'), ('BUNCH', 'Botte'), ('BASKET', 'Panier')], default='KG', max_length=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('5.50'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_seasonal', models.BooleanField(default=True)),
                ('season_start_month', models.IntegerField(blank=True, null=True)),
                ('season_end_month', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sfs_products.productcategory')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['category', 'name'],
            },
        ),
    ]
